### ISSUE TITLE
Update to create 0.5.1.e

### ISSUE THREAD

**Issue by ghost** [RuochenFu21/CreateEnderTransmission#11]
Hello,
Create has launched a new version, and it breaks a lot of add-ons, including this one.
Could you fix it ?

**Comment by ghost** [comment]
Here the logs
```
[21/09/2023 23:22:04 PM] Caused by: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
[21/09/2023 23:22:04 PM] 	at TRANSFORMER/createendertransmission@2.0.4-1.20.1/com.forsteri.createendertransmission.entry.TransmissionBlocks.<clinit>(TransmissionBlocks.java:25)
[21/09/2023 23:22:04 PM] 	at TRANSFORMER/createendertransmission@2.0.4-1.20.1/com.forsteri.createendertransmission.CreateEnderTransmission.<init>(CreateEnderTransmission.java:36)
[21/09/2023 23:22:04 PM] 	... 14 more
[21/09/2023 23:22:04 PM] [modloading-worker-0/ERROR] Failed to create mod instance. ModID: createendertransmission, class com.forsteri.createendertransmission.CreateEnderTransmission
```

**Comment by furuochen-dev** [comment]
Unable to reproduce

**Comment by ghost** [comment]
With Forge, just use the last version of Create A.K.A 0.5.1.e with ender Transmission 2.0.4
And you get Create Ender Transmission has failed to load correctly
Java.lang.reflect.InvocationTargetException: null

**Comment by Siryak** [comment]
With Forge, just use the last version of Create A.K.A 0.5.1.e with ender Transmission 2.0.4
And you get Create Ender Transmission has failed to load correctly
Java.lang.reflect.InvocationTargetException: null

**Comment by SquidBoiiiiii** [comment]
im getting the same thing here. idk why its doing it. well, thats why im here lol

**Comment by billjk2013** [comment]
i'm getting the same issue here along with a few other create addon mods all after updating to 0.5.1e

**Comment by furuochen-dev** [comment]
Patched for Forge 1.20

**Comment by furuochen-dev** [comment]
Unable to reproduce in other versions

**Comment by billjk2013** [comment]
Thank you
 loaded right up
