### ISSUE TITLE
Incompatibility with create 0.5.1

### ISSUE THREAD

**Issue by JerryHan3** [RuochenFu21/CreateEnderTransmission#5]
This mod has failed to load with create 0.5.1b version, and here's the relative crash log: 
```
-- MOD createendertransmission --
Details:
	Mod File: /D:/Game/Minecraft/Server/.minecraft/versions/Mod Trial 3/mods/[机械动力：末影传输] createendertransmission-1.0.0.jar
	Failure message: Create Ender Transmission (createendertransmission) has failed to load correctly
		java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
	Mod Version: 1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullSupplier com.simibubi.create.foundation.data.CreateRegistrate.lazy(java.lang.String)'
Stacktrace:
	at net.forsteri.createendertransmission.CreateEnderTransmission.<clinit>(CreateEnderTransmission.java:69) ~[%5B机械动力：末影传输%5D%20createendertransmission-1.0.0.jar%2370!/:1.0.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.4.jar%2399!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.4.jar%2398!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

**Comment by furuochen-dev** [comment]
OFC, use the current newest version
